export const catImages = {
    'abyssinian.jpg': require('./abyssinian.jpg'),
    'american-shorthair.jpg': require('./american-shorthair.jpg'),
    'bengal.jpg': require('./bengal.jpg'),
    'birman.jpg': require('./birman.jpg'),
    'british-shorthair.jpg': require('./british-shorthair.jpg'),
    'burmese.jpg': require('./burmese.jpg'),
    'chartreux.jpg': require('./chartreux.jpg'),
    'cornish-rex.jpg': require('./cornish-rex.jpg'),
    'devon-rex.jpg': require('./devon-rex.jpg'),
    'egyptian-mau.jpg': require('./egyptian-mau.jpg'),
    'european-shorthair.jpg': require('./european-shorthair.jpg'),
    'exotic-shorthair.jpg': require('./exotic-shorthair.jpg'),
    'japanese-bobtail.jpg': require('./japanese-bobtail.jpg'),
    'korat.jpg': require('./korat.jpg'),
    'laperm.jpg': require('./laperm.jpg'),
    'maine-coon.jpg': require('./maine-coon.jpg'),
    'manx.jpg': require('./manx.jpg'),
    'munchkin.jpg': require('./munchkin.jpg'),
    'norwegian-forest.jpg': require('./norwegian-forest.jpg'),
    'ocicat.jpg': require('./ocicat.jpg'),
    'oriental-shorthair.jpg': require('./oriental-shorthair.jpg'),
    'persian.jpg': require('./persian.jpg'),
    'placeholder.jpg': require('./placeholder.jpg'),
    'ragdoll.jpg': require('./ragdoll.jpg'),
    'russian-blue.jpg': require('./russian-blue.jpg'),
    'scottish-fold.jpg': require('./scottish-fold.jpg'),
    'siamese.jpg': require('./siamese.jpg'),
    'siberian.jpg': require('./siberian.jpg'),
    'singapura.jpg': require('./singapura.jpg'),
    'somali.jpg': require('./somali.jpg'),
    'sphynx.jpg': require('./sphynx.jpg'),
    'tonkinese.jpg': require('./tonkinese.jpg'),
    'turkish-angora.jpg': require('./turkish-angora.jpg'),
    'turkish-van.jpg': require('./turkish-van.jpg'),
  };

export type CatImageKey = keyof typeof catImages;
